### PR TITLE
Use jQuery's param implementation to build data params 

### PR DESCRIPTION
**Pull request by hulufei**
Hi, currently qwest have some issues when serialize array data, I found it's better to use jQuery's param function to build data params, and someone have just extracted an individual module [jquery-param](https://github.com/knowledgecode/jquery-param), which is nice.

I don't know what's the best way to require additional modules, we need package for minified version, this PR works fine for webpack (and also browserify I guess).

### CODE REVIEW

**Comment by pyrsmk** [comment]
What the issues you have encounter?
In all cases, I think it's a great idea to rely on another library.

For that, we'll need to support all environments : nodejs, webpack, browserify or just the browser. I think we should deploy 2 library versions : one with the requires, and one with all dependencies included. So, I should update the build system.

Since I've planned to externalize the promises behavior to another library for the `2.0` release, I think we'll add this PR to it when it will be available.

**Comment by hulufei** [comment]
@pyrsmk Here is the issue

Say I want to post an array data to the server, like: `qwest.post(url, { list: [1, 2, 3] })`, I got posted data like this: `list[0]=1&list[1]=2&list[3]=3`, which can't be handled properly in the server. The expected result is `list[]=1&list[]=2&list[]=3`. More explanation can be found [here](http://stackoverflow.com/questions/5497093/what-is-traditional-style-of-param-serialization-in-jquery).

Looking forward `2.0` release, it sounds great:)

**Comment by pyrsmk** [comment]
Really interesting, thanks for the link ;)

**Comment by pyrsmk** [comment]
Since this issue is part of #51, I close it. We'll implement this for the `2.0` release ;)

**Comment by message** [comment]
@pyrsmk this is an issue for me now too. Java recognizes parameter bag as `param=value1&param=value2` and there is no way to specify that in qwest

```java
@POST
@Consumes(MediaType.APPLICATION_FORM_URLENCODED)
public Response createAdminUser(@FormParam("parameters") List<String> permissions)
{
	return Response.status(Response.Status.BAD_REQUEST).entity("").build();
}
```

```
POST /api/v1/administrators HTTP/1.1
Accept: application/json
Content-Type: application/x-www-form-urlencoded

parameters=first_parameter&parameters=second_parameter
```
screen shot 2015-07-08 at 16 39 56

**Comment by pyrsmk** [comment]
I think I'll consider implementing this soon, then. Since the `2.0` is a complete rewrite, with the help from  @singerxt , it takes some time.

I'll fix it tomorrow if possible.

**Comment by singerxt** [comment]
I believe this issue is fixed in 2.0 :-)

**Comment by pyrsmk** [comment]
The 2.0 does not seem to have all the functionnality of qwest 1.7. Am I wrong? Oo

**Comment by pyrsmk** [comment]
( this ticket is still alive, hold on :p )

**Pull request closed without merging**
