### PR TITLE
[ES6] MVP get, post, delete working

### PR DESCRIPTION
**Pull request by singerxt**

### CODE REVIEW

**Comment by pyrsmk** [comment]
Sorry, I'm a bit late ;) I saw your code and it seems quite weel. I think I'll only modify some lines, at the end of the ES6 development, with how features are implemented in the current qwest release (because it avoids several bugs).

I'm also learning ES6 for another project so I'll can help you as well.

What is you `app.js` file? Is it for tests?

**Comment by singerxt** [comment]
@pyrsmk No worries I also didnt have time in last week. :-) 

Yes in this file you can test current work just after git clone es6 branch.

```
npm install
gulp watch // Run file watcher, linter, babel and server + rest api emulator.
```

**Comment by pyrsmk** [comment]
Ok ^^ I'll take a look to that in the next future :p 

Hey! Do you know how to import modules into ES5 browser context? I successfully babelified my library but I don't how to make it accessible in the browser. I can't find a way with using AMD modules in the ES6 class. But it shouldn't the good way to do that...

**Comment by singerxt** [comment]
@pyrsmk Could you send code example ?

**Comment by pyrsmk** [comment]
Let's imagine, I have a simple : 

```javascript
class Library {}
```

In this class I import some files with the ES6's import. Anyway, when I'm in the browser I want to do a `var lib = new Library()` or `var lib = require('lib')`. But it seems I can't require the file. The class seems to be well build so I don't understand. Here's the gulpfile I wrote : 

```js
gulp.task('build', function() {
	
	browserify({
			entries: './src/Horizon.js',
			debug: true
		})
		.transform(babelify)
		.bundle()
		.pipe(source('Horizon.min.js'))
		.pipe(buffer())
		.pipe(gulp.dest('.'));
	
	return gulp.src([
			'./bower_components/hamster/hamster.js',
			'./bower_components/impetus/impetus.js',
			'./bower_components/scrolling/standalone/scrolling.js',
			'Horizon.min.js'
		])
		.pipe(uglify())
		.pipe(concat('Horizon.min.js') )
		.pipe(gulp.dest('.'));
	
});
```

**Comment by singerxt** [comment]
Unfortunately for now you won't be able to do that. All dependiences need to be compiled be babel or browserify. ;-)

**Comment by pyrsmk** [comment]
That is what I'm doing. No?

**Comment by pyrsmk** [comment]
Ah, no, I understand what you're talking about ^^

**Comment by pyrsmk** [comment]
Hum...So... There's no simple way to use ES6 qwest in a browser context?

**Comment by singerxt** [comment]
Of course it is ;-) Babel compiling code to ES5. So still qwest could be used in ES5 projects from global object.

**Comment by pyrsmk** [comment]
Ok. It seems it's the only way indeed ^^

**Comment by pyrsmk** [comment]
But it won't be available for RequireJS/CommonJS environments in the browser, if I'm right?

**Comment by singerxt** [comment]
I think should be available as CommonJS. I will think about require js support.

**Comment by pyrsmk** [comment]
Ok, we'll see ;)

**Pull request merged**
