### PR TITLE
Allow falsy values in request body

### PR DESCRIPTION
**Pull request by Koji23**

### CODE REVIEW

**Comment by pyrsmk** [comment]
Hi,

Can you explain what issue/context it fixes?

**Comment by rahuljiresal** [comment]
It fixes the case where the body is a boolean `false`. Earlier, because the way Javascript treats that, the actual data being sent in the request ended up being `null` instead of `false`.

**Comment by pyrsmk** [comment]
Ok, I didn't know sending `false` as data could be a valid use case.

**Comment by pyrsmk** [comment]
I'll merge that in the day and bump a new version.

**Pull request merged**
