### PR TITLE
Update qwest.js

### PR DESCRIPTION
**Pull request by gfogle**
Support HTTP PATCH

### CODE REVIEW

**Comment by pyrsmk** [comment]
Hi! Instead of your PR, and since I'm currently updating qwest, I think I'll add a `map()` method to add specific HTTP requests. What do you think?

**Comment by gfogle** [comment]
Sounds fine to me. Can we merge my PR still so my other repo can pull? Otherwise I'll have to keep working off my fork for PATCH method.

George

**Comment by pyrsmk** [comment]
Hum. I can be complicated since my local version will be different from the remote version (if I merge your changes). I don't like git very much when we must deal with different file versions.

Is it blocking for you? I think I'll push a new version this week-end.

**Comment by gfogle** [comment]
yea its blocking for bulk perf using patch instead of put

**Comment by pyrsmk** [comment]
Ok, I merge it, then ;)

**Comment by pyrsmk** [comment]
I won't create releases from this source file. If it's a problem, tell me ;)

**Comment by gfogle** [comment]
sweet. thanks!

**Comment by gfogle** [comment]
sweet. as long as i can pull in package file with updates thats ok.

**Comment by pyrsmk** [comment]
What package file?
You're talking about NPM?

**Pull request merged**
